[workspace]
members = [
    "bins/revme",
    "bins/revm-test",
    "crates/revm",
    "crates/primitives",
    "crates/interpreter",
    "crates/precompile",
    "tests/openvm/tests",
]
resolver = "2"
default-members = ["crates/revm"]

[workspace.dependencies]
# openvm
openvm = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-ecc-guest = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-pairing-guest = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-keccak256-guest = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-sdk = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-build = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-pairing-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-rv32im-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-algebra-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-algebra-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-ecc-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-ecc-transpiler = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-pairing-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-circuit = { git = "ssh://git@github.com/openvm-org/openvm.git" }
openvm-stark-sdk = { git = "ssh://git@github.com/openvm-org/stark-backend.git" }

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3
