[workspace]
members = ["bins/revme", "bins/revm-test", "crates/revm", "crates/primitives", "crates/interpreter", "crates/precompile", "tests/openvm/tests"]
resolver = "2"
default-members = ["crates/revm"]

[workspace.dependencies]
# openvm stark-backend
openvm-stark-sdk = { git = "ssh://git@github.com/axiom-crypto/stark-backend-private.git", rev = "738c68157058a0f95d4b9e96deb01b1f36309bfa" }
# openvm
openvm = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-circuit = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-transpiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-build = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-sdk = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
# openvm extensions
openvm-ecc-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-pairing-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-keccak256-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-sha256-guest = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-pairing-transpiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-rv32im-transpiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-algebra-circuit = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-algebra-transpiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-ecc-circuit = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-ecc-transpiler = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
openvm-pairing-circuit = { git = "ssh://git@github.com/axiom-crypto/openvm-private.git", rev = "4264a006249d7f82620578a622148d8c7d3d337f" }
# openvm external lib
openvm-kzg = { git = "https://github.com/axiom-crypto/openvm-kzg.git", rev = "480372aa04dc0b3c2df2a9d31fe5a4c84a8cf13c", default-features = false }

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3

[profile.fast]
inherits = "test"
opt-level = 1
