[workspace]
members = ["bins/revme", "bins/revm-test", "crates/revm", "crates/primitives", "crates/interpreter", "crates/precompile", "tests/openvm/tests"]
resolver = "2"
default-members = ["crates/revm"]

[workspace.dependencies]
# openvm stark-backend
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", rev = "738c68157058a0f95d4b9e96deb01b1f36309bfa" }
# openvm
openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-build = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
# openvm extensions
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-pairing-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-keccak256-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-sha256-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-pairing-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-rv32im-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-algebra-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-algebra-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-ecc-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-ecc-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
openvm-pairing-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "411e2a2f042c5e86407eaa8b18974d04ca1aba11" }
# openvm external lib
openvm-kzg = { git = "https://github.com/axiom-crypto/openvm-kzg.git", rev = "e1b37d72c7705e2ac26b5d22e30b1e3d2474cb6b", default-features = false }

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3

[profile.fast]
inherits = "test"
opt-level = 1
