[workspace]
members = ["bins/revme", "bins/revm-test", "crates/revm", "crates/primitives", "crates/interpreter", "crates/precompile", "tests/openvm/tests"]
resolver = "2"
default-members = ["crates/revm"]

[workspace.dependencies]
# openvm stark-backend
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", rev = "bc364134b8315c27bfd29c6e77ac79fe77090137" }
# openvm
openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-build = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
# openvm extensions
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-pairing-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-keccak256-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-sha256-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-pairing-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-rv32im-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-algebra-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-algebra-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-ecc-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-ecc-transpiler = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
openvm-pairing-circuit = { git = "https://github.com/openvm-org/openvm.git", rev = "4285a4f974db90ce11bd21c0642d059cbb8975d0" }
# openvm external lib
openvm-kzg = { git = "https://github.com/axiom-crypto/openvm-kzg.git", rev = "af38f584e4bfd8a237c1f66bb68c1d00f5a2a61b", default-features = false }

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3

[profile.fast]
inherits = "test"
opt-level = 1
